#!/usr/bin/env node
/**
 * Generates dist/sitemap.xml from the pages that are actually in the build.
 *
 * Runs after `vite build`, so it sees the real output: the React entry plus every static
 * page copied out of public/. Add a page, it appears; delete one, it disappears. Nobody
 * has to remember to edit XML, which is the only way a hand-written sitemap stays honest.
 *
 * Two deliberate choices:
 *
 *  · It scans dist/, not public/. A sitemap generated from source can list a URL that
 *    failed to build; one generated from the output cannot.
 *
 *  · There is no priority or changefreq. Google has said publicly that it ignores both.
 *    They were noise that still had to be maintained.
 *
 * lastmod comes from the file's last commit, not its mtime — in CI every file is written
 * at clone time, so an mtime-based sitemap claims the whole site changed on every deploy.
 * If git is unavailable the date is simply omitted, which is valid.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { join, posix, relative } from 'node:path';
import { promisify } from 'node:util';

const run = promisify(execFile);

const DIST = 'dist';
const ORIGIN = 'https://www.seekolabs.tech';

/** Every .html file under dist/, as paths relative to dist/. */
async function pages(dir = DIST, found = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) await pages(full, found);
    else if (entry.name.endsWith('.html')) found.push(full);
  }
  return found;
}

/** dist/ludo-apex/index.html -> /ludo-apex/ ; dist/a/b.html -> /a/b.html */
function toUrl(file) {
  const rel = relative(DIST, file).split(/[\\/]/).join('/');
  return '/' + (rel.endsWith('index.html') ? rel.slice(0, -'index.html'.length) : rel);
}

/** dist/ludo-apex/x.html -> public/ludo-apex/x.html ; dist/index.html -> index.html */
function toSource(file) {
  const rel = relative(DIST, file).split(/[\\/]/).join('/');
  return rel === 'index.html' ? 'index.html' : posix.join('public', rel);
}

async function lastCommitDate(source) {
  try {
    const { stdout } = await run('git', ['log', '-1', '--format=%cs', '--', source]);
    const d = stdout.trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(d) ? d : null;
  } catch {
    return null;                        // no git, shallow clone, or file never committed
  }
}

const files = (await pages()).sort();
const urls = [];

for (const file of files) {
  const html = await readFile(file, 'utf8');
  // Respect a page's own opt-out rather than keeping a list of exceptions here.
  if (/<meta[^>]+name=["']robots["'][^>]+noindex/i.test(html)) continue;
  urls.push({ loc: ORIGIN + toUrl(file), lastmod: await lastCommitDate(toSource(file)) });
}

// Shortest paths first, so the homepage leads and sections group under it.
urls.sort((a, b) => a.loc.length - b.loc.length || a.loc.localeCompare(b.loc));

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs during the build. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ''}
  </url>`).join('\n')}
</urlset>
`;

await writeFile(join(DIST, 'sitemap.xml'), xml, 'utf8');
console.log(`sitemap: ${urls.length} url${urls.length === 1 ? '' : 's'}`);
for (const u of urls) console.log(`  ${u.loc}${u.lastmod ? `  (${u.lastmod})` : ''}`);
