import { CPAOffer, Campaign, ConferenceEvent, GeoStat, PostbackLog, Vertical } from './types';

export const INITIAL_OFFERS: CPAOffer[] = [
  {
    id: 'OFF-101',
    title: 'Cyber Realm Online - RPG MMORPG',
    vertical: 'Games',
    payout: 4.80,
    payoutType: 'CPL',
    epc: 1.45,
    cr: 12.8,
    geos: ['USA', 'DEU', 'GBR', 'FRA', 'JPN'],
    allowedTraffic: ['Popunder', 'In-Page Push', 'Native', 'Banners'],
    description: 'High converting free-to-play sci-fi alien strategy game. Converts on email registration & account creation.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Low',
    badge: 'Trending Game',
    rating: 4.9,
    conversionFlow: 'Single Opt-In (SOI)',
    featured: true
  },
  {
    id: 'OFF-102',
    title: 'Live Cam Stars - HD Premium Stream',
    vertical: 'Webcam',
    payout: 38.50,
    payoutType: 'CPA',
    epc: 2.10,
    cr: 9.4,
    geos: ['USA', 'CAN', 'AUS', 'GBR', 'DEU', 'NLD'],
    allowedTraffic: ['Popunder', 'Push', 'Native', 'Direct Domain'],
    description: 'Top adult live webcam platform. High RevShare and aggressive CPA payout on first purchase or token credit top-up.',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Optimal Risk',
    badge: 'High EPC',
    rating: 4.8,
    conversionFlow: 'First Credit Purchase',
    featured: true
  },
  {
    id: 'OFF-103',
    title: 'Golden Slots 777 - Lucky Casino',
    vertical: 'iGaming',
    payout: 145.00,
    payoutType: 'CPA',
    epc: 4.25,
    cr: 6.8,
    geos: ['DEU', 'AUT', 'BRA', 'MEX', 'CAN', 'GBR'],
    allowedTraffic: ['Popunder', 'Native', 'In-Page Push', 'Search'],
    description: 'Licensed global online casino with $1,000 welcome bonus + 100 free spins. Payout triggered on minimum $15 deposit.',
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Low',
    badge: 'Top Converter',
    rating: 5.0,
    conversionFlow: 'First Time Deposit (FTD)',
    featured: true
  },
  {
    id: 'OFF-104',
    title: 'MatchPassion - Casual Adult Dating',
    vertical: 'Dating',
    payout: 6.20,
    payoutType: 'CPL',
    epc: 1.85,
    cr: 14.2,
    geos: ['USA', 'GBR', 'AUS', 'DEU', 'ITA'],
    allowedTraffic: ['In-Page Push', 'Popunder', 'Social', 'Native'],
    description: 'Global casual dating platform with geo-smart landing page routing. Converts fast on male traffic SOI.',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Low',
    badge: 'Fast Payout',
    rating: 4.7,
    conversionFlow: 'Double Opt-In (DOI)',
    featured: true
  },
  {
    id: 'OFF-105',
    title: 'CineStream 4K - Unlimited VOD Movies',
    vertical: 'Video-on-Demand',
    payout: 22.00,
    payoutType: 'CPS',
    epc: 2.40,
    cr: 11.1,
    geos: ['USA', 'CAN', 'ES', 'FRA', 'BRA', 'IND'],
    allowedTraffic: ['Popunder', 'In-Page Push', 'Direct Domain'],
    description: 'Stream latest movies & TV shows in 4K HDR. $1 trial for 3 days converts with high CC submit rates.',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Optimal Risk',
    badge: 'CC Trial',
    rating: 4.9,
    conversionFlow: '$1 Trial Credit Card',
    featured: true
  },
  {
    id: 'OFF-106',
    title: 'Champions Bet - Football & Sportsbook',
    vertical: 'Betting',
    payout: 110.00,
    payoutType: 'CPA',
    epc: 3.90,
    cr: 7.5,
    geos: ['GBR', 'DEU', 'BRA', 'NGA', 'KEN', 'ESP'],
    allowedTraffic: ['In-Page Push', 'Popunder', 'Native', 'Banners'],
    description: 'Premier sportsbook covering UEFA, Premier League, NFL, NBA. Payout on $10 minimum bet or deposit.',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Low',
    badge: 'Sports Season',
    rating: 4.9,
    conversionFlow: 'FTD ($10 Min)',
    featured: true
  },
  {
    id: 'OFF-107',
    title: 'KetoGlow Thermo - Fat Burner Booster',
    vertical: 'Nutra',
    payout: 85.00,
    payoutType: 'CPS',
    epc: 3.10,
    cr: 8.9,
    geos: ['USA', 'CAN', 'AUS', 'GBR'],
    allowedTraffic: ['Native', 'Search', 'In-Page Push', 'Social'],
    description: 'Top-selling keto supplement for weight loss. High converting VSL (Video Sales Letter) landing page with trial bottle upsells.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Low',
    badge: 'VSL Winner',
    rating: 4.8,
    conversionFlow: 'Straight Sale (SS)',
    featured: true
  },
  {
    id: 'OFF-108',
    title: 'iPhone 16 Pro Mystery Box Sweeps',
    vertical: 'Sweeps',
    payout: 28.00,
    payoutType: 'CPA',
    epc: 1.95,
    cr: 15.6,
    geos: ['USA', 'FRA', 'ITA', 'ESP', 'DEU'],
    allowedTraffic: ['Popunder', 'In-Page Push', 'Native'],
    description: 'Popular gadget sweepstakes entry with $2 shipping fee CC submit. Massive volume potential.',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    riskScore: 'Optimal Risk',
    badge: 'Viral Vol',
    rating: 4.6,
    conversionFlow: 'CC Submit',
    featured: false
  }
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'CMP-9001',
    name: 'US-iGaming-GoldenSlots-PopUnder-Tier1',
    offerId: 'OFF-103',
    offerTitle: 'Golden Slots 777 - Lucky Casino',
    vertical: 'iGaming',
    status: 'Active',
    format: 'Popunder',
    targetGeos: ['DEU', 'AUT', 'CAN'],
    bidType: 'CPT',
    bidAmount: 0.0035,
    dailyBudget: 250,
    totalBudget: 2500,
    spent: 842.30,
    impressions: 240600,
    clicks: 18450,
    conversions: 18,
    revenue: 2610.00,
    createdAt: '2026-08-01'
  },
  {
    id: 'CMP-9002',
    name: 'EU-Dating-MatchPassion-Push-Volume',
    offerId: 'OFF-104',
    offerTitle: 'MatchPassion - Casual Adult Dating',
    vertical: 'Dating',
    status: 'Active',
    format: 'In-Page Push',
    targetGeos: ['USA', 'GBR', 'DEU'],
    bidType: 'CPC',
    bidAmount: 0.045,
    dailyBudget: 150,
    totalBudget: 1500,
    spent: 412.50,
    impressions: 112000,
    clicks: 9160,
    conversions: 114,
    revenue: 706.80,
    createdAt: '2026-08-04'
  },
  {
    id: 'CMP-9003',
    name: 'Global-Games-CyberRealm-Pop-Scale',
    offerId: 'OFF-101',
    offerTitle: 'Cyber Realm Online - RPG MMORPG',
    vertical: 'Games',
    status: 'Active',
    format: 'Popunder',
    targetGeos: ['USA', 'FRA', 'JPN'],
    bidType: 'CPT',
    bidAmount: 0.0022,
    dailyBudget: 100,
    totalBudget: 1000,
    spent: 198.40,
    impressions: 90180,
    clicks: 6420,
    conversions: 82,
    revenue: 393.60,
    createdAt: '2026-08-08'
  },
  {
    id: 'CMP-9004',
    name: 'Betting-ChampionsBet-Football-Season',
    offerId: 'OFF-106',
    offerTitle: 'Champions Bet - Football & Sportsbook',
    vertical: 'Betting',
    status: 'Paused',
    format: 'Native Ads',
    targetGeos: ['GBR', 'ESP', 'BRA'],
    bidType: 'CPC',
    bidAmount: 0.12,
    dailyBudget: 300,
    totalBudget: 3000,
    spent: 650.00,
    impressions: 45000,
    clicks: 5410,
    conversions: 12,
    revenue: 1320.00,
    createdAt: '2026-07-28'
  }
];

export const INITIAL_CONFERENCES: ConferenceEvent[] = [
  {
    id: 'CONF-01',
    title: 'Meet SeekoLabs at G Gate Conf',
    subtitle: 'Traffic & CPA Performance Summit',
    date: '26 - 27 June 2026',
    location: 'Georgia, Tbilisi',
    flag: '🇬🇪',
    booth: 'Booth #B-14',
    badge: 'Exclusive Invitation',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'CONF-02',
    title: 'SeekoLabs @ Affiliate World Europe',
    subtitle: 'Global CPA Media Buying Expo',
    date: '12 - 14 July 2026',
    location: 'Barcelona, Spain',
    flag: '🇪🇸',
    booth: 'Booth #A-02',
    badge: 'VIP Lounge Host',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'CONF-03',
    title: 'iGaming & AdTech Expo 2026',
    subtitle: 'AI Automated Bidding & Tracking',
    date: '15 - 17 September 2026',
    location: 'Limassol, Cyprus',
    flag: '🇨🇾',
    booth: 'Main Stage Sponsor',
    badge: 'Keynote Speaker',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80'
  }
];

export const INITIAL_GEO_STATS: GeoStat[] = [
  { country: 'United States', code: 'USA', flag: '🇺🇸', conversions: 432, revenue: 14250.00, share: 38 },
  { country: 'Germany', code: 'DEU', flag: '🇩🇪', conversions: 310, revenue: 9800.00, share: 26 },
  { country: 'United Kingdom', code: 'GBR', flag: '🇬🇧', conversions: 215, revenue: 6400.00, share: 17 },
  { country: 'Canada', code: 'CAN', flag: '🇨🇦', conversions: 120, revenue: 3850.00, share: 10 },
  { country: 'Brazil', code: 'BRA', flag: '🇧🇷', conversions: 98, revenue: 3200.00, share: 9 }
];

export const INITIAL_POSTBACK_LOGS: PostbackLog[] = [
  { id: 'PB-8801', clickId: 'clk_89f2a9c12a', campaignId: 'CMP-9001', offerId: 'OFF-103', payout: 145.00, geo: 'DEU', status: 'Success', timestamp: '10 mins ago' },
  { id: 'PB-8802', clickId: 'clk_33d9x0e881', campaignId: 'CMP-9002', offerId: 'OFF-104', payout: 6.20, geo: 'USA', status: 'Success', timestamp: '18 mins ago' },
  { id: 'PB-8803', clickId: 'clk_77b1e4210a', campaignId: 'CMP-9003', offerId: 'OFF-101', payout: 4.80, geo: 'FRA', status: 'Success', timestamp: '24 mins ago' },
  { id: 'PB-8804', clickId: 'clk_110a39fbc8', campaignId: 'CMP-9001', offerId: 'OFF-103', payout: 145.00, geo: 'AUT', status: 'Success', timestamp: '31 mins ago' },
  { id: 'PB-8805', clickId: 'clk_44991x2a0c', campaignId: 'CMP-9002', offerId: 'OFF-104', payout: 6.20, geo: 'GBR', status: 'Success', timestamp: '42 mins ago' }
];

export const INITIAL_ANALYTICS_HOURLY = [
  { time: '00:00', impressions: 14200, clicks: 1210, conversions: 14, spend: 58.20, revenue: 198.00, roi: 240.2 },
  { time: '03:00', impressions: 18500, clicks: 1480, conversions: 19, spend: 72.00, revenue: 268.00, roi: 272.2 },
  { time: '06:00', impressions: 22100, clicks: 1950, conversions: 28, spend: 95.50, revenue: 412.00, roi: 331.4 },
  { time: '09:00', impressions: 34000, clicks: 3100, conversions: 42, spend: 148.00, revenue: 680.00, roi: 359.4 },
  { time: '12:00', impressions: 48900, clicks: 4200, conversions: 58, spend: 210.00, revenue: 990.00, roi: 371.4 },
  { time: '15:00', impressions: 52100, clicks: 4850, conversions: 69, spend: 242.00, revenue: 1240.00, roi: 412.3 },
  { time: '18:00', impressions: 45200, clicks: 3910, conversions: 51, spend: 198.00, revenue: 890.00, roi: 349.5 },
  { time: '21:00', impressions: 31200, clicks: 2890, conversions: 36, spend: 135.00, revenue: 540.00, roi: 300.0 }
];
